version: '3.9'
services:
  specs:
    image: ruby:3.1.3
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env.docker
    stop_signal: SIGKILL
    command: "tail -F /dev/null"
